export interface Theme {
  background: string;
  headerFooterBg: string;
  rowBg: string;
  rowActiveBorder: string;
  resultTileBg: string;
  resultTileBorder: string;
  inlineBtnBg: string;
  inlineBtnText: string;
  trashBtnBg: string;
  deleteBg: string;
  lineNumColor: string;
  addLineBorder: string;
  addLineText: string;
  resetBorder: string;
  resetText: string;
  snapshotBorder: string;
  snapshotBorderDisabled: string;
  snapshotText: string;
  submitBg: string;
  submitDisabledBg: string;
  primaryText: string;
  tokenText: string;
  tokenStale: string;
  tokenSubColor: string;
  tokenSubStale: string;
  cursorDefault: string;
  cursorActive: string;
  placeholder: string;
  resultNull: string;
  resultExact: string;
  resultClose: string;
  resultFar: string;
  numberTileBg: string;
  numberTileDisabledBg: string;
  numberTileDisabledText: string;
  operatorBtnBg: string;
  operatorBtnDisabledBg: string;
  operatorBtnDisabledText: string;
  targetBg: string;
  targetLabel: string;
  targetNumber: string;
  dotSolving: string;
  dotSolvable: string;
  dotUnsolvable: string;
  bannerExactBg: string;
  bannerCloseBg: string;
  bannerOffBg: string;
  bannerText: string;
  solutionBoxBg: string;
  solutionLabel: string;
  solutionExpr: string;
  newGameBg: string;
}

export const darkTheme: Theme = {
  background: '#0d1117',
  headerFooterBg: '#0d1117',
  rowBg: '#1a1a2e',
  rowActiveBorder: '#1565c0',
  resultTileBg: '#263238',
  resultTileBorder: '#546e7a',
  inlineBtnBg: '#263238',
  inlineBtnText: '#eceff1',
  trashBtnBg: '#37474f',
  deleteBg: '#b71c1c',
  lineNumColor: '#546e7a',
  addLineBorder: '#37474f',
  addLineText: '#607d8b',
  resetBorder: '#b71c1c',
  resetText: '#e57373',
  snapshotBorder: '#1565c0',
  snapshotBorderDisabled: '#37474f',
  snapshotText: '#90caf9',
  submitBg: '#1565c0',
  submitDisabledBg: '#263238',
  primaryText: '#ffffff',
  tokenText: '#e0e0e0',
  tokenStale: '#e53935',
  tokenSubColor: '#546e7a',
  tokenSubStale: '#b71c1c',
  cursorDefault: 'rgba(255, 255, 255, 0.1)',
  cursorActive: '#64b5f6',
  placeholder: '#555',
  resultNull: '#888',
  resultExact: '#4caf50',
  resultClose: '#ff9800',
  resultFar: '#90caf9',
  numberTileBg: '#c47500',
  numberTileDisabledBg: '#3a3a3a',
  numberTileDisabledText: '#888',
  operatorBtnBg: '#2d5a8e',
  operatorBtnDisabledBg: '#333',
  operatorBtnDisabledText: '#666',
  targetBg: '#c0392b',
  targetLabel: '#ffcdd2',
  targetNumber: '#ffffff',
  dotSolving: '#ffffff',
  dotSolvable: '#69f0ae',
  dotUnsolvable: 'rgba(255, 100, 100, 0.35)',
  bannerExactBg: '#1b5e20',
  bannerCloseBg: '#e65100',
  bannerOffBg: '#37474f',
  bannerText: '#ffffff',
  solutionBoxBg: '#1a237e',
  solutionLabel: '#90caf9',
  solutionExpr: '#ffffff',
  newGameBg: '#2e7d32',
};

export const lightTheme: Theme = {
  background: '#f5f5f5',
  headerFooterBg: '#f5f5f5',
  rowBg: '#ffffff',
  rowActiveBorder: '#1976d2',
  resultTileBg: '#e0e0e0',
  resultTileBorder: '#90a4ae',
  inlineBtnBg: '#e0e0e0',
  inlineBtnText: '#1a1a2e',
  trashBtnBg: '#cfd8dc',
  deleteBg: '#b71c1c',
  lineNumColor: '#78909c',
  addLineBorder: '#b0bec5',
  addLineText: '#546e7a',
  resetBorder: '#b71c1c',
  resetText: '#c62828',
  snapshotBorder: '#1976d2',
  snapshotBorderDisabled: '#b0bec5',
  snapshotText: '#1565c0',
  submitBg: '#1976d2',
  submitDisabledBg: '#bdbdbd',
  primaryText: '#1a1a1a',
  tokenText: '#212121',
  tokenStale: '#c62828',
  tokenSubColor: '#78909c',
  tokenSubStale: '#b71c1c',
  cursorDefault: 'rgba(0, 0, 0, 0.08)',
  cursorActive: '#1565c0',
  placeholder: '#9e9e9e',
  resultNull: '#9e9e9e',
  resultExact: '#4caf50',
  resultClose: '#ff9800',
  resultFar: '#1565c0',
  numberTileBg: '#e67e00',
  numberTileDisabledBg: '#bdbdbd',
  numberTileDisabledText: '#757575',
  operatorBtnBg: '#1565c0',
  operatorBtnDisabledBg: '#e0e0e0',
  operatorBtnDisabledText: '#9e9e9e',
  targetBg: '#c62828',
  targetLabel: '#ffffff',
  targetNumber: '#ffffff',
  dotSolving: '#ffffff',
  dotSolvable: '#69f0ae',
  dotUnsolvable: 'rgba(255, 100, 100, 0.35)',
  bannerExactBg: '#388e3c',
  bannerCloseBg: '#e64a19',
  bannerOffBg: '#546e7a',
  bannerText: '#ffffff',
  solutionBoxBg: '#e8eaf6',
  solutionLabel: '#1565c0',
  solutionExpr: '#1a1a2e',
  newGameBg: '#388e3c',
};
